# Generated by Django 5.0.6 on 2024-05-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_board_colour_column_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='task',
            new_name='board',
        ),
    ]
