# Generated by Django 5.0.6 on 2024-05-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_task_column_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='task',
            new_name='board',
        ),
    ]
