# Generated by Django 5.0.6 on 2024-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_label_board_alter_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(),
        ),
    ]
