# Generated by Django 5.0.6 on 2024-05-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_column_board_alter_label_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_to_task', to='main.task')),
            ],
        ),
    ]
