# Generated by Django 5.0.6 on 2024-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_board_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='has_archived_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
