# Generated by Django 5.0.6 on 2024-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_board_has_archived_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='updated_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='completed_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
