# Generated by Django 5.0.6 on 2024-05-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_board_updated_on_alter_subtask_completed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
