# Generated by Django 5.0.6 on 2024-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_task_options_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='completed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
