# Generated by Django 5.0.6 on 2024-05-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_board_author_alter_label_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='updated_on',
        ),
    ]
