# Generated by Django 5.0.6 on 2024-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_board_author_alter_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(),
        ),
    ]
