# Generated by Django 5.0.6 on 2024-05-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_column_title_alter_label_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='colour',
            field=models.CharField(default='white', max_length=300),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='label',
            name='colour',
            field=models.CharField(default='light', max_length=300),
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
