# Generated by Django 5.0.6 on 2024-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_subtask_task_alter_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
