# Generated by Django 5.0.6 on 2024-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_subtask_completed_on_alter_task_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column_position',
            field=models.IntegerField(default=0),
        ),
    ]
