# Generated by Django 5.0.6 on 2024-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_column_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
