# Generated by Django 5.0.6 on 2024-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=105),
        ),
    ]
