# Generated by Django 5.0.6 on 2024-05-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_subtask_title_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
